---

- name: Configuring docker
  template:
    src: etc-default-docker.j2
    dest: /etc/default/docker
    owner: root
    group: root
    mode: "0644"
  notify: restart docker

- name: Configuring logrotate
  template:
    src: etc-logrotate.d-docker.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: "0644"
