---

ansible:
#  verbose: true
  playbook: tests/test.yml
  extra_vars:
    docker_swarm_addr: "{{ ansible_all_ipv4_addresses | select('match', '172.28.128.*') | first }}"

# configuration options for the internal call to vagrant
vagrant:

  # molecule's --platform option will look for these names
  platforms:
    - name: centos-7
      box: centos/7
    - name: ubuntu-16.04
      box: bento/ubuntu-16.04
    - name: ubuntu-14.04
      box: bento/ubuntu-14.04

  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2048
        cpus: 2

  instances:
    - name: ansible-dockerswarm-01
      ansible_groups:
        - docker_engine
        - docker_swarm_manager
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
      options:
        append_platform_to_hostname: yes
    - name: ansible-dockerswarm-02
      ansible_groups:
        - docker_engine
        - docker_swarm_manager
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
      options:
        append_platform_to_hostname: yes
    - name: ansible-dockerswarm-03
      ansible_groups:
        - docker_engine
        - docker_swarm_worker
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
      options:
        append_platform_to_hostname: yes
