---

docker_repo: main
# docker_repo: testing
# docker_repo: experimental

# Extra packages that have to installed together with Docker
docker_dependencies: "{{ default_docker_dependencies }}"

# Switches disabling the docker-engine or swarm-mode setup.
skip_engine: False
skip_swarm: False

docker_swarm_interface: eth0
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_port: 2377
# docker_swarm_secret: "supersecret"
