---
dependencies: []

galaxy_info:
  author: Tobias Schifftner
  description: Installs and configures ntp and defines timezone on Debian/Ubuntu linux servers.
  company: ambimax® GmbH
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - precise
    - trusty
  galaxy_tags:
    - ubuntu
    - debian
    - ntp
    - timezone
