---

galaxy_info:
  author: Andrea Tosatto
  description: Setup a Docker Swarm Cluster on Centos/RHEL, Ubuntu/Debian.
  company: "Purple Ocean S.r.l."
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - trusty
        - utopic
        - vivid
        - wily
        - xenial
    - name: Debian
      versions:
        - jessie
  galaxy_tags:
    - docker
    - swarm
    - docker-swarm
    - docker-cluster

dependencies: []
